---

- name: Fetch Servers
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Fetch Openstack Servers
      os_server_info:
        cloud: openstack
        region_name: regionOne
      register: servers

    # - name: Debug Results
    #   debug:
    #     var: servers

    - name: Add Server
      add_host:
        name: "{{ item.public_v4 }}"
        ansible_user: cloud-user
        ansible_ssh_private_key_file: "~/.ssh/test_id_rsa"
        groups:
          - "{{ item.metadata.group }}"
          - "{{ item.metadata.deployment_name }}"
      loop: "{{ servers.openstack_servers }}"

- name: Subscription
  hosts: all
  tasks:
    redhat_subscription:
      state: present
      activationkey: AnsibleTraining
      org_id: 13572854
      auto_attach: yes

- import_playbook: provision_database_tier.yml
- import_playbook: provision_load_balancer_tier.yml
- import_playbook: provision_app_tier.yml
